version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pucfarma_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
    ports:
      - "5432:5432"